# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Neighborhood.destroy_all

neighborhoods = Neighborhood.create(
  [{:name => 'Beverly Grove'},
  {:name => 'Beverlywood'},
  {:name => 'Brentwood'},
  {:name => 'Century City'},
  {:name => 'Cheviot Hills'},
  {:name => 'Del Rey'},
  {:name => 'Fairfax District'},
  {:name => 'Ladera Heights'},
  {:name => 'Mar Vista'},
  {:name => 'Mid-Wilshire'},
  {:name => 'Pacific Palisades'},
  {:name => 'Palms'},
  {:name => 'Pico-Robertson'},
  {:name => 'Playa del Rey'},
  {:name => 'Playa Vista'},
  {:name => 'Rancho Park'},
  {:name => 'Sawtelle'},
  {:name => 'Venice'},
  {:name => 'West Los Angeles'},
  {:name => 'Westchester'},
  {:name => 'Westwood'},
  {:name => 'Central LA'},
  {:name => 'Eastside'},
  {:name => 'Harbor'},
  {:name => 'Northeast LA'},
  {:name => 'Pomona Valley'},
  {:name => 'San Fernando Valley'},
  {:name => 'San Gabriel Valley'},
  {:name => 'South Bay'},
  {:name => 'South LA'},
  {:name => 'Southeast'},
  {:name => 'Verdugos'},
  ])


carpools = Carpool.create([
  {:name => 'Super Awesome MM Carpool', :neighborhood => Neighborhood.find_by(:name => 'Miracle Mile')},
  {:name => 'Cool Brentwood Carpool', :neighborhood => Neighborhood.find_by(:name => 'Brentwood')},
  {:name => 'Westwood Folk Rock Commuters', :neighborhood => Neighborhood.find_by(:name => 'Westwood')}
  ])

  #
  # [{:name => 'Bel-Air'},
  #  {:name => 'Arlington Heights'},
  #  {:name => 'Beverly Hills'},
  #  {:name => 'Beverly Wood'},
  #  {:name => 'Beverly Crest'},
  #  {:name => 'Brentwood'},
  #  {:name => 'Carthay'},
  #  {:name => 'Central LA'},
  #  {:name => 'Century City'},
  #  {:name => 'Cheviot Hills'},
  #  {:name => 'Chinatown'},
  #  {:name => 'Culver City'},
  #  {:name => 'Del Ray'},
  #  {:name => 'Downtown'},
  #  {:name => 'East Hollywood'},
  #  {:name => 'Eastside'},
  #  {:name => 'Echo Park'},
  #  {:name => 'Elysian Park'},
  #  {:name => 'Elysian Valley'},
  #  {:name => 'Ladera Heights'},
  #  {:name => 'Griffith Park'},
  #  {:name => 'Hancock Park'},
  #  {:name => 'Harvard Heights'},
  #  {:name => 'Hollywood'},
  #  {:name => 'Hollywood Hills'},
  #  {:name => 'Hollywood Hills West'},
  #  {:name => 'Koreatown'},
  #  {:name => 'Larchmont'},
  #  {:name => 'Los Feliz'},
  #  {:name => 'Mar Vista'},
  #  {:name => 'Marina del Ray'},
  #  {:name => 'Mid-City'},
  #  {:name => 'Mid-Wilshire'},
  #  {:name => 'Northeast LA'},
  #  {:name => 'Pacific Palisades'},
  #  {:name => 'Palms'},
  #  {:name => 'Pico-Robertson'},
  #  {:name => 'Pico-Union'},
  #  {:name => 'Playa Vista'},
  #  {:name => 'Rancho Park'},
  #  {:name => 'San Fernando Valley'},
  #  {:name => 'San Gabriel Valley'},
  #  {:name => 'Santa Monica'},
  #  {:name => 'Sawtelle'},
  #  {:name => 'Silver Lake'},
  #  {:name => 'South Bay'},
  #  {:name => 'South LA'},
  #  {:name => 'Southeast LA'},
  #  {:name => 'Venice'},
  #  {:name => 'West Hollywood'},
  #  {:name => 'West LA'},
  #  {:name => 'Westlake'},
  #  {:name => 'Westwood'},
  #  {:name => 'Windsor Square'}]
